"""empty message

Revision ID: 0b033507c88a
Revises: cab17e626d64
Create Date: 2022-04-29 20:17:12.946576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b033507c88a'
down_revision = 'cab17e626d64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('data', sa.LargeBinary(), nullable=False))
    op.add_column('image', sa.Column('extention', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image', 'extention')
    op.drop_column('image', 'data')
    # ### end Alembic commands ###
