"""remove  models

Revision ID: 348e7e446e44
Revises: c415f3c292e1
Create Date: 2022-04-29 20:39:52.397983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '348e7e446e44'
down_revision = 'c415f3c292e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('card')
    op.drop_table('deck')
    op.drop_table('image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('data', sa.BLOB(), nullable=False),
    sa.Column('extention', sa.VARCHAR(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deck',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=128), nullable=False),
    sa.Column('color', sa.VARCHAR(length=7), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('card',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=128), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('deck_id', sa.INTEGER(), nullable=False),
    sa.Column('image_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['deck_id'], ['deck.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
