"""removed image column from card model

Revision ID: 3e8df0a26f10
Revises: 28df9ef8dc87
Create Date: 2022-04-29 17:42:21.228649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e8df0a26f10'
down_revision = '28df9ef8dc87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card', 'image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('image', sa.BLOB(), nullable=True))
    # ### end Alembic commands ###
