"""empty message

Revision ID: 5ed27186ce41
Revises: 8234b655460f
Create Date: 2022-04-29 21:11:30.812475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ed27186ce41'
down_revision = '8234b655460f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'card', type_='foreignkey')
    op.drop_column('card', 'image_id')
    op.add_column('image', sa.Column('card_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'image', 'card', ['card_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'image', type_='foreignkey')
    op.drop_column('image', 'card_id')
    op.add_column('card', sa.Column('image_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'card', 'image', ['image_id'], ['id'])
    # ### end Alembic commands ###
