"""create image model data and extention and make them non nullable

Revision ID: c23bfeb6ea55
Revises: fc941c6c1cc2
Create Date: 2022-04-29 18:12:38.467095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c23bfeb6ea55'
down_revision = 'fc941c6c1cc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('data', sa.LargeBinary(), nullable=False))
    op.add_column('image', sa.Column('extention', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image', 'extention')
    op.drop_column('image', 'data')
    # ### end Alembic commands ###
