"""remove card model

Revision ID: c415f3c292e1
Revises: 8d3cc61d21d8
Create Date: 2022-04-29 20:35:28.209144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c415f3c292e1'
down_revision = '8d3cc61d21d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'card', 'image', ['image_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'card', type_='foreignkey')
    # ### end Alembic commands ###
