"""remove image model data and extention

Revision ID: fc941c6c1cc2
Revises: cbee2e9441ed
Create Date: 2022-04-29 18:11:54.650865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc941c6c1cc2'
down_revision = 'cbee2e9441ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image', 'data')
    op.drop_column('image', 'extention')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('extention', sa.VARCHAR(length=10), nullable=True))
    op.add_column('image', sa.Column('data', sa.BLOB(), nullable=True))
    # ### end Alembic commands ###
